$(document).ready(function () {
    $("#mosaferan").click(function () { $(this).toggleClass('mosaferanClick'); if ($(this).hasClass('mosaferanClick')) { var dumHeight = $('#mosaferan-panel').height() + $('.header-nav').height() + 65 + 'px'; $("#mosaferan-panel").stop('true,true').slideDown("800"); $('.dumbTourSlider').animate({ 'top': dumHeight }, 400) } else { $("#mosaferan-panel").stop('true,true').slideUp("600"); $('.dumbTourSlider').animate({ 'top': '107px' }, 400) }; }); $(".navbar-toggle").click(function () { $(this).toggleClass('showResponsiveMenu'); if ($(this).hasClass('showResponsiveMenu')) { $(".menuItemWrap").stop('true,true').slideDown("800"); } else { $(".menuItemWrap").stop('true,true').slideUp("600"); }; }); $(window).scroll(function () { var scroll = $(window).scrollTop(); if (scroll >= 393) { $(".pillar").addClass("fix-pillar"); } else { $(".pillar").removeClass("fix-pillar"); } }); $(window).scroll(function () { var scroll = $(window).scrollTop(); if (scroll >= 383) { $(".title-tab-holder").addClass("fix-title-tab-holder"); } else { $(".title-tab-holder").removeClass("fix-title-tab-holder"); } });
    var offset = 220;
    var duration = 500;
    jQuery(window).scroll(function () {
        if (jQuery(this).scrollTop() > offset)
        { jQuery('.back-to-top').fadeIn(duration); }
        else
        { jQuery('.back-to-top').fadeOut(duration); }
    });
    jQuery('.back-to-top').click(function (event) { event.preventDefault(); jQuery('html, body').animate({ scrollTop: 0 }, duration); return false; });



    $("#button").click(function () { $('html, body').animate({ scrollTop: $("#myDiv").offset().top }, 2000); }); var config = { '.chosen-select': {}, '.chosen-select-deselect': { allow_single_deselect: true }, '.chosen-select-no-single': { disable_search_threshold: 10 }, '.chosen-select-no-results': { no_results_text: 'Ø¬ÙˆØ§Ø¨ÛŒ ÛŒØ§ÙØª Ù†Ø´Ø¯' }, '.chosen-select-width': { width: "95%" } }; for (var selector in config) { $(selector).chosen(config[selector]); }; var elements = $('.summary-hybrid').children('.summeryR').length; var sumWidth = 100 / elements; $('.summary-hybrid .summeryR').css('width', sumWidth + '%'); $(".division-city").each(function () { $(this).contents('h2').contents('a').click(function (event) { $('.isActive').removeClass('isActive'); var dt = $(this).parents('.division-city').attr('data-name'); if ($('#' + dt).css('display') == "none") { $(this).parents('.division-city').addClass('isActive'); $('.division-city-list').slideUp(); $('#' + dt).stop(true, true).slideDown(); event.preventDefault(); } else { $(this).contents('h2').contents('a').css('pointer-events', ' auto'); $(this).parents('.division-city').removeClass('isActive'); }; }); }); $(".lstContainer").click(function () { $(this).toggleClass('jnva'); if ($(this).hasClass('jnva')) { var content_show = $(this).attr("data-name"); if ($("#" + content_show).siblings('.lstContainer').hasClass('jnva')) { $("#" + content_show).siblings('.lstContainer').not(this).removeClass('jnva'); $("#" + content_show).siblings('.division-lastsecond-tour-list').hide(); $("#" + content_show).slideDown(); } else { $("#" + content_show).slideDown(); } } else { var content_show = $(this).attr("data-name"); $("#" + content_show).slideUp(); }; }); $(".tabItem").click(function (event) { event.preventDefault(); var xOffset = $(this).attr('href'); $('html, body').animate({ scrollTop: $(xOffset).offset().top - 60 }, 1000); }); $('select').css('direction', 'rtl'); $("#showFilterPanel").click(function () { $(this).toggleClass('showFilterPanel'); $(this).next('.sideFilter').toggleClass('showSideFilter'); }); $('.closeTheDiv').click(function () { $(this).parent('.division-city-list').slideUp('600'); $('.division-city').removeClass('isActive'); }); $('.otherPrice').parent('span').addClass('dbSpan'); $(document).bind('cbox_open', function () { $('html').css({ overflow: 'hidden' }); }).bind('cbox_closed', function () { $('html').css({ overflow: '' }); }); wsfHomeResposive(); $(window).resize(wsfHomeResposive); $('#closead').click(function () { $('.ads').hide('600'); });
});